# Cloud Build configuration for Google Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/modern-webapp:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/modern-webapp:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'modern-webapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/modern-webapp:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - 'bilan-competence-449414:us-central1:modern-webapp-db'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'AUTH_SECRET=auth-secret:latest,DATABASE_URL=database-url:latest'

images:
  - 'gcr.io/$PROJECT_ID/modern-webapp:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY