FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies
RUN npm ci

# Generate Prisma client
RUN npx prisma generate

# Copy migration files
COPY prisma ./prisma

# Set entrypoint
ENTRYPOINT ["npx", "prisma"]